#! /usr/bin/env python3

import argparse

# Parse arguments
parser = argparse.ArgumentParser()
parser.add_argument("FASTA", type=argparse.FileType('r'), help="FASA file")
parser.add_argument("coverage", type=int, help="get coverage")
parser.add_argument("sampling", type=int, help="get sampling")

args = parser.parse_args()
